development:
  host: localhost
  adapter: postgresql
  database: trogde_development

staging:
  adapter: postgresql
  database: trogde_staging

production:
  adapter: postgresql
  database: trogde_production
  pool: 5

test:
  host: localhost
  adapter: postgresql
  database: trogde_test
